FROM gradle:6.5.0-jdk14

ENV ROOT_FOLDER alive_sim
COPY --from=0 . /$ROOT_FOLDER
#COPY --chown=gradle:gradle . /$ROOt_FOLDER
USER root
RUN chown -R gradle /$ROOT_FOLDER
#RUN mkdir /$ROOt_FOLDER && chown gradle: /$ROOt_FOLDER
USER gradle
WORKDIR /$ROOT_FOLDER

CMD["gradlew", "cleanTest", "test", "-Dmicronaut.environments=test"]
#RUN ./gradlew build
